import { Router, Request, Response } from 'express';
import { db } from '../lib/db';
import { validateYear, validateMonth } from '../lib/validation';

export const emailTemplatesRouter = Router();

emailTemplatesRouter.get('/', (_req: Request, res: Response) => {
  res.json([
    { id: 'accountant-package', name: 'Accountant Package Send', description: 'Monthly package email to your accountant/CPA' },
    { id: 'escalation', name: 'Internal Escalation', description: 'Flag a tax issue to the team with severity level' },
    { id: 'missing-statement', name: 'Missing Statement Follow-up', description: 'Request a missing bank statement from a team member' },
  ]);
});

emailTemplatesRouter.get('/accountant-package', async (req: Request, res: Response) => {
  const { companyId } = req.query;
  const year = req.query.year ? validateYear(req.query.year) : undefined;
  const month = req.query.month ? validateMonth(req.query.month) : undefined;
  try {
    let companyName = 'All Companies', shortCode = '', jurisdiction = '';
    if (companyId) {
      const { rows } = await db.query('SELECT name, short_code, jurisdiction FROM companies WHERE id = $1', [companyId]);
      if (rows[0]) { companyName = rows[0].name || rows[0].short_code; shortCode = rows[0].short_code; jurisdiction = rows[0].jurisdiction; }
    }
    const monthName = month ? new Date(year as number, month - 1).toLocaleString('en', { month: 'long', year: 'numeric' }) : `FY ${year}`;
    const subject = `Monthly Tax Package — ${companyName} — ${monthName}`;
    const body = `Hi [Accountant Name],\n\nPlease find attached the monthly bookkeeping and tax package for ${companyName} for ${monthName}.\n\nThis package includes:\n- Monthly Profit & Loss report (Excel)${jurisdiction === 'QC' ? '\n- TPS/TVQ remittance summary (PDF)' : ''}\n- Bank statement PDFs\n- Subcontractor invoices (if applicable)\n\nKey highlights:\n- [Total Revenue: $X,XXX.XX]\n- [Total Expenses: $X,XXX.XX]\n- [Net Income: $X,XXX.XX]${jurisdiction === 'QC' ? '\n- [TPS Net Owing: $X,XXX.XX]\n- [TVQ Net Owing: $X,XXX.XX]' : ''}\n\nPlease confirm receipt and let me know if you need any clarification.\n\nThank you,\n[Your Name]\n${companyName}${shortCode ? ` (${shortCode})` : ''}\n\n---\nGenerated by Tax Dashboard on ${new Date().toLocaleDateString('en-CA')}`;
    res.json({ subject, body, type: 'accountant-package' });
  } catch (err: any) { res.status(500).json({ error: err.message }); }
});

emailTemplatesRouter.get('/escalation', async (req: Request, res: Response) => {
  const { companyId, issue, severity } = req.query;
  try {
    let companyName = '';
    if (companyId) { const { rows } = await db.query('SELECT name, short_code FROM companies WHERE id = $1', [companyId]); if (rows[0]) companyName = rows[0].name || rows[0].short_code; }
    const severityLabel = severity === 'high' ? 'URGENT' : severity === 'medium' ? 'Action Required' : 'FYI';
    const subject = `[${severityLabel}] Tax Issue — ${companyName || 'Multiple Companies'}`;
    const body = `Team,\n\nThis is an ${severityLabel.toLowerCase()} regarding ${companyName || 'the following companies'}.\n\nIssue:\n${issue || '[Describe the issue here]'}\n\nImpact:\n- [Which filings/periods are affected]\n- [Estimated financial impact]\n\nRecommended Action:\n- [ ] [Action item 1]\n- [ ] [Action item 2]\n\nTimeline:\n- Issue identified: ${new Date().toLocaleDateString('en-CA')}\n- Action needed by: [DATE]\n\nPlease acknowledge receipt.\n\nRegards,\n[Your Name]\n\n---\nSeverity: ${severityLabel}\nGenerated by Tax Dashboard`;
    res.json({ subject, body, type: 'escalation' });
  } catch (err: any) { res.status(500).json({ error: err.message }); }
});

emailTemplatesRouter.get('/missing-statement', async (req: Request, res: Response) => {
  const { companyId } = req.query;
  const year = req.query.year ? validateYear(req.query.year) : undefined;
  const month = req.query.month ? validateMonth(req.query.month) : undefined;
  try {
    let companyName = '', bankName = '';
    if (companyId) {
      const { rows } = await db.query('SELECT name, short_code FROM companies WHERE id = $1', [companyId]);
      if (rows[0]) companyName = rows[0].name || rows[0].short_code;
      const { rows: accounts } = await db.query('SELECT bank_name FROM bank_accounts WHERE company_id = $1 AND is_active = true', [companyId]);
      if (accounts.length) bankName = accounts.map((a: any) => a.bank_name).join(', ');
    }
    const monthName = month ? new Date(year as number, month - 1).toLocaleString('en', { month: 'long', year: 'numeric' }) : '';
    const subject = `Missing Bank Statement — ${companyName} — ${monthName}`;
    const body = `Hi,\n\nI'm following up on the bank statement for ${companyName} for ${monthName}.\n\nWe are still missing the statement from: ${bankName || '[Bank Name]'}\n\nCould you please:\n1. Download the statement from your online banking portal\n2. Save it as a PDF\n3. Upload it to the Tax Dashboard\n\nThank you,\n[Your Name]\n\n---\nGenerated by Tax Dashboard on ${new Date().toLocaleDateString('en-CA')}`;
    res.json({ subject, body, type: 'missing-statement' });
  } catch (err: any) { res.status(500).json({ error: err.message }); }
});
