import { Router, Request, Response } from 'express';
import { db } from '../lib/db';
import PDFDocument from 'pdfkit';
import { calculateNetTax } from '../services/taxCalculator';
import { validateYear, validateMonth } from '../lib/validation';

export const pdfExportsRouter = Router();

function fmt(n: number): string { return '$' + n.toFixed(2).replace(/\B(?=(\d{3})+(?!\d))/g, ','); }
function drawInfoBox(doc: PDFKit.PDFDocument, rows: string[][]) {
  doc.fontSize(10).font('Helvetica');
  for (const [label, value] of rows) { doc.font('Helvetica-Bold').text(`${label}: `, { continued: true }); doc.font('Helvetica').text(value); }
}
function drawTable(doc: PDFKit.PDFDocument, rows: string[][]) {
  doc.fontSize(10).font('Helvetica');
  for (const row of rows) {
    if (row.every(c => c === '')) { doc.moveDown(0.2); continue; }
    const isBold = row[0] === 'NET OWING' || row[0].startsWith('Net ') || row[0].startsWith('Total');
    doc.font(isBold ? 'Helvetica-Bold' : 'Helvetica');
    if (row.length === 3) { const x = doc.x; doc.text(row[0], x, doc.y, { width: 250 }); const y = doc.y - doc.currentLineHeight(); doc.text(row[1], x + 260, y, { width: 100, align: 'right' }); doc.text(row[2], x + 370, y, { width: 100, align: 'right' }); }
    else { doc.text(`${row[0]}`, { continued: true, width: 300 }); doc.text(row[1] || '', { align: 'right' }); }
  }
}

pdfExportsRouter.get('/tps-tvq/:companyId', async (req: Request, res: Response) => {
  const year = validateYear(req.query.year), month = validateMonth(req.query.month);
  if (!year || !month) { res.status(400).json({ error: 'Invalid year/month parameter' }); return; }
  try {
    const { rows: compRows } = await db.query('SELECT * FROM companies WHERE id = $1', [req.params.companyId]);
    const company = compRows[0];
    if (!company) { res.status(404).json({ error: 'Company not found' }); return; }
    const startDate = `${year}-${String(month).padStart(2, '0')}-01`;
    const endDate = new Date(year, month, 0).toISOString().slice(0, 10);
    const monthName = new Date(year, month - 1).toLocaleString('en', { month: 'long', year: 'numeric' });
    const { rows: transactions } = await db.query('SELECT * FROM transactions WHERE company_id = $1 AND is_reviewed = true AND date >= $2 AND date <= $3 ORDER BY date', [req.params.companyId, startDate, endDate]);
    let totalIncome = 0, totalExpenses = 0, quebecSales = 0, otherSales = 0, tpsCollected = 0, tvqCollected = 0, tpsITC = 0, tvqITR = 0, mealExpenses = 0;
    const incomeByCategory: Record<string, number> = {}, expenseByCategory: Record<string, number> = {};
    for (const t of transactions) {
      if (t.category === 'income_loan_received' || t.category === 'expense_loan_repayment') continue;
      if (t.type === 'credit') { totalIncome += Number(t.amount); incomeByCategory[t.category] = (incomeByCategory[t.category] || 0) + Number(t.amount); quebecSales += Number(t.quebec_sales_amount || 0); otherSales += Number(t.ontario_sales_amount || 0) + Number(t.us_sales_amount || 0) + Number(t.other_canada_sales_amount || 0) + Number(t.international_sales_amount || 0); }
      else { totalExpenses += Number(t.amount); expenseByCategory[t.category] = (expenseByCategory[t.category] || 0) + Number(t.amount); if (t.category === 'expense_meals_entertainment') mealExpenses += Number(t.amount); }
      tpsCollected += Number(t.tps_collectable || 0); tvqCollected += Number(t.tvq_collectable || 0); tpsITC += Number(t.tps_reclaimable || 0); tvqITR += Number(t.tvq_reclaimable || 0);
    }
    const { tpsNetOwing, tvqNetOwing } = calculateNetTax(tpsCollected, tvqCollected, tpsITC, tvqITR);
    const doc = new PDFDocument({ size: 'LETTER', margins: { top: 50, bottom: 50, left: 50, right: 50 } });
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=TPS-TVQ_${company.short_code}_${year}-${String(month).padStart(2, '0')}.pdf`);
    doc.pipe(res);
    doc.fontSize(20).font('Helvetica-Bold').text('TPS/TVQ REMITTANCE SUMMARY', { align: 'center' });
    doc.moveDown(0.3);
    doc.fontSize(10).font('Helvetica').fillColor('#666666').text('Generated by Tax Dashboard', { align: 'center' });
    doc.moveDown(1.5);
    doc.fillColor('#000000');
    drawInfoBox(doc, [['Company', company.name || company.short_code], ['Short Code', company.short_code], ['TPS Number', company.tps_number || 'Not provided'], ['TVQ Number', company.tvq_number || 'Not provided'], ['Period', monthName], ['Period Dates', `${startDate} to ${endDate}`]]);
    doc.moveDown(1);
    doc.fontSize(14).font('Helvetica-Bold').text('REVENUE SUMMARY');
    doc.moveDown(0.5);
    drawTable(doc, [['Total Revenue', fmt(totalIncome)], ['Quebec Sales (taxable)', fmt(quebecSales)], ['Other Sales (non-QC)', fmt(otherSales)]]);
    doc.moveDown(0.3);
    doc.fontSize(10).font('Helvetica').fillColor('#666666').text('Revenue by Category:');
    doc.fillColor('#000000');
    for (const [cat, amount] of Object.entries(incomeByCategory)) doc.fontSize(9).text(`  ${cat}: ${fmt(amount)}`);
    doc.moveDown(1);
    doc.fontSize(14).font('Helvetica-Bold').text('TPS/TVQ CALCULATION');
    doc.moveDown(0.5);
    drawTable(doc, [['', 'TPS (5%)', 'TVQ (9.975%)'], ['Tax Collected on Sales', fmt(tpsCollected), fmt(tvqCollected)], ['Input Tax Credits / Refunds', `(${fmt(tpsITC)})`, `(${fmt(tvqITR)})`], ['', '', ''], ['NET OWING', fmt(tpsNetOwing), fmt(tvqNetOwing)]]);
    doc.moveDown(0.5);
    const totalOwing = tpsNetOwing + tvqNetOwing;
    doc.fontSize(12).font('Helvetica-Bold').fillColor(totalOwing >= 0 ? '#CC0000' : '#006600').text(totalOwing >= 0 ? `TOTAL OWING: ${fmt(totalOwing)}` : `REFUND DUE: ${fmt(Math.abs(totalOwing))}`);
    doc.fillColor('#000000').moveDown(1);
    doc.fontSize(8).font('Helvetica').fillColor('#999999').text('This report is for informational purposes only. Confirm with your fiscaliste before filing.', { align: 'center' });
    doc.end();
  } catch (err: any) { res.status(500).json({ error: err.message || 'Failed to generate PDF' }); }
});

pdfExportsRouter.get('/cover-note/:companyId', async (req: Request, res: Response) => {
  const year = validateYear(req.query.year), month = validateMonth(req.query.month);
  if (!year || !month) { res.status(400).json({ error: 'Invalid year/month parameter' }); return; }
  try {
    const { rows: compRows } = await db.query('SELECT * FROM companies WHERE id = $1', [req.params.companyId]);
    const company = compRows[0];
    if (!company) { res.status(404).json({ error: 'Company not found' }); return; }
    const startDate = `${year}-${String(month).padStart(2, '0')}-01`;
    const endDate = new Date(year, month, 0).toISOString().slice(0, 10);
    const monthName = new Date(year, month - 1).toLocaleString('en', { month: 'long', year: 'numeric' });
    const [{ rows: stmts }, { rows: invs }, { rows: txns }] = await Promise.all([
      db.query('SELECT file_name FROM statements WHERE company_id = $1 AND period_start >= $2 AND period_end <= $3', [req.params.companyId, startDate, endDate]),
      db.query('SELECT vendor_name, amount, currency FROM invoices WHERE company_id = $1 AND invoice_date >= $2 AND invoice_date <= $3', [req.params.companyId, startDate, endDate]),
      db.query('SELECT type, amount, tps_collectable, tvq_collectable, tps_reclaimable, tvq_reclaimable, is_reviewed FROM transactions WHERE company_id = $1 AND date >= $2 AND date <= $3', [req.params.companyId, startDate, endDate]),
    ]);
    let tpsC = 0, tvqC = 0, tpsI = 0, tvqI = 0, flaggedCount = 0;
    for (const t of txns) { if (!t.is_reviewed) flaggedCount++; tpsC += Number(t.tps_collectable || 0); tvqC += Number(t.tvq_collectable || 0); tpsI += Number(t.tps_reclaimable || 0); tvqI += Number(t.tvq_reclaimable || 0); }
    const doc = new PDFDocument({ size: 'LETTER', margins: { top: 60, bottom: 60, left: 60, right: 60 } });
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=CoverNote_${company.short_code}_${year}-${String(month).padStart(2, '0')}.pdf`);
    doc.pipe(res);
    doc.fontSize(18).font('Helvetica-Bold').text('ACCOUNTANT PACKAGE', { align: 'center' });
    doc.fontSize(14).font('Helvetica').text(`${company.name || company.short_code} — ${monthName}`, { align: 'center' });
    doc.moveDown(2);
    doc.fontSize(11).font('Helvetica').text(`Date: ${new Date().toLocaleDateString('en-CA')}`);
    doc.moveDown(1.5);
    doc.fontSize(13).font('Helvetica-Bold').text('CONTENTS:');
    doc.moveDown(0.5);
    doc.fontSize(11).font('Helvetica');
    doc.text('- Monthly P&L report (Excel)');
    if (company.jurisdiction === 'QC') doc.text('- TPS/TVQ remittance summary (PDF)');
    doc.text('- Bank statements:');
    if (stmts.length === 0) doc.text('    (none uploaded for this period)');
    else for (const s of stmts) doc.text(`    ${s.file_name}`);
    doc.text('- Subcontractor invoices:');
    if (invs.length === 0) doc.text('    (none for this period)');
    else for (const inv of invs) doc.text(`    ${inv.vendor_name} — ${fmt(Number(inv.amount))} ${inv.currency}`);
    doc.moveDown(1.5);
    if (company.jurisdiction === 'QC') { doc.fontSize(13).font('Helvetica-Bold').text('TAX SUMMARY:'); doc.moveDown(0.5); doc.fontSize(11).font('Helvetica').text(`TPS Net Owing: ${fmt(tpsC - tpsI)}`).text(`TVQ Net Owing: ${fmt(tvqC - tvqI)}`).text(`Combined: ${fmt((tpsC - tpsI) + (tvqC - tvqI))}`); doc.moveDown(1); }
    if (flaggedCount > 0) { doc.fontSize(13).font('Helvetica-Bold').fillColor('#CC0000').text('FLAGGED FOR YOUR REVIEW:'); doc.fontSize(11).font('Helvetica').fillColor('#CC0000').text(`${flaggedCount} unreviewed transaction(s).`); doc.fillColor('#000000').moveDown(1); }
    doc.fontSize(11).font('Helvetica').text('Please confirm all items and advise on any adjustments.');
    doc.moveDown(3);
    doc.fontSize(9).fillColor('#999999').text('Generated by Tax Dashboard. Not a substitute for professional accounting review.', { align: 'center' });
    doc.end();
  } catch (err: any) { res.status(500).json({ error: err.message || 'Failed to generate cover note' }); }
});
